name: CI [Development]
on:
  push:
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "public/**"
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Initializing
        run: |
          rm -rf .git
          git config --global init.defaultBranch master
          git init
          git config user.name "NweOo Developer"
          git config user.email "nweoo22222@yandex.com"
      - name: Committing
        run: |
          git add .
          git commit -m 'auto push from Github Workflow (development)'
      - name: Add Remote
        run: |
          git remote add origin https://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@github.com/etherio97/nwe-oo-vue
      - name: Pushing
        run: |
          git push origin master --force
